language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t bjornhona/beerio-test -f beerio-frontend/Dockerfile.dev ./beerio-frontend

script:
  - docker run -e CI=true bjornhona/beerio-test npm test

after_success:
  - docker build -t bjornhona/multi-beerio-backend ./beerio-backend
  - docker build -t bjornhona/multi-beerio-frontend ./beerio-frontend
  - docker build -t bjornhona/multi-nginx ./nginx
  # Login to the docker CLI"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker
  - docker push bjornhona/multi-beerio-backend
  - docker push bjornhona/multi-beerio-frontend
  - docker push bjornhona/multi-beerio-nginx