FROM node:13.12.0-alpine
# FROM node:alpine
# FROM node:13.12.0-alpine as builder
# FROM node:alpine as builder
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "start"]

FROM nginx
EXPOSE 80
COPY --from=0 /app/build /usr/share/nginx/html
# COPY --from=builder /app/build /usr/share/nginx/html