FROM node:alpine
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
# CMD ["npm", "run", "start"]
CMD ["npm", "run", "test"]

FROM nginx
EXPOSE 80
COPY --from=0 /app/beerio-frontend/build /usr/share/nginx/html